### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by fyodoriv** [himynameisdave/joke-me#1]
Hey, nice joke. ;]

But after installing it with
`npm i -g joke-me`
I had to also run
`npm i -g commander`
and
`npm i -g request-promise`
Because I was getting 

```
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/cbrwizard/.nvm/versions/node/v5.0.0/lib/node_modules/joke-me/index.js:3:20)
```

and

```
Error: Cannot find module 'request-promise'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/cbrwizard/.nvm/versions/node/v5.0.0/lib/node_modules/joke-me/index.js:5:20)
```

Maybe moving these dependencies from devDependencies to dependencies in package.json can help?

**Comment by skurpi** [comment]
Got the same thing!

``` cmd
$ node -v
v4.2.1

$ npm i -g joke-me
/usr/local/bin/joke-me -> /usr/local/lib/node_modules/joke-me/index.js
joke-me@0.1.0 /usr/local/lib/node_modules/joke-me
└── clor@2.0.0 (ansi-styles@2.1.0)

$ joke-me
module.js:339
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/joke-me/index.js:3:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by bchelli** [comment]
Fix https://github.com/himynameisdave/joke-me/pull/2
